<script type="text/javascript">
Validation.creditCartTypes = $H({
  'VISA'   : [new RegExp('^4[0-9]{12}([0-9]{3})?$'), new RegExp('^[0-9]{3}$'), true],
  'MC'     : [new RegExp('^5[1-5][0-9]{14}$'), new RegExp('^[0-9]{3}$'), true],
  'AMEX'   : [new RegExp('^3[47][0-9]{13}$'), new RegExp('^[0-9]{4}$'), true],
  'DELTA'  : [false, new RegExp('^([0-9]{3}|[0-9]{4})?$'), false],
  'MAESTRO': [false, new RegExp('^([0-9]{3}|[0-9]{4})?$'), false],
  'UKE'    : [false, new RegExp('^([0-9]{3}|[0-9]{4})?$'), false],
  'SOLO'   : [false, new RegExp('^([0-9]{3}|[0-9]{4})?$'), false]
});
</script>
<?php $_code=$this->getMethodCode() ?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none">
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_owner"><?php echo Mage::helper('payment')->__('Name on Card') ?> <span class="required">*</span></label><br/>
            <input type="text" title="<?php echo Mage::helper('payment')->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->getInfoData('cc_owner') ?>"/>
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_type"><?php echo Mage::helper('payment')->__('Credit Card Type') ?> <span class="required">*</span></label><br/>
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
            <?php $_ccType = $this->getInfoData('cc_type') ?>
                <option value=""></option>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>" <?php if($_typeCode==$_ccType): ?>selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_number"><?php echo Mage::helper('payment')->__('Credit Card Number') ?> <span class="required">*</span></label><br/>
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo Mage::helper('payment')->__('Credit Card Number') ?>" class="input-text validate-cc-number" value="<?php echo $this->getInfoData('cc_number')?>"/>
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?> <span class="required">*</span></label><br/>
            <select id="<?php echo $_code ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="required-entry">
            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                <option value="<?php echo $k ?>" <?php if($k==$_ccExpMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
            </select>
            <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
            <select id="<?php echo $_code ?>_expiration_yr" style="width:103px;" name="payment[cc_exp_year]" class="required-entry">
            <?php foreach ($this->getCcYears() as $k=>$v): ?>
                <option value="<?php echo $k ? $k : '' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <?php if($this->hasVerification()): ?>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_cid"><?php echo Mage::helper('payment')->__('Card Verification Number') ?> <span class="required">*</span></label><br/>
            <input type="text" title="<?php echo Mage::helper('payment')->__('Card Verification Number') ?>" class="required-entry input-text validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" style="width:3em;" value="<?php echo $this->getInfoData('cc_cid')?>"/>
        </div>
    </li>
    <?php endif; ?>
    <li>
	    <p>
		You need to fill in the following fields <b>ONLY</b> if the information is on your card.
		<b>NOTE:</b> Halifax, Bank of Scotland and Abbey customers do not need to enter an issue number.
		</p>
    </li>

	    <li>
	        <div class="input-box">
	            <label for="<?php echo $_code ?>_start"><?php echo Mage::helper('payment')->__('Start Date') ?></label><br/>
	            <select id="<?php echo $_code ?>_start" style="width:140px;" name="payment[cc_start_month]">
	            <?php $_ccStartMonth = $this->getInfoData('cc_start_month') ?>
	            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
	                <option value="<?php echo $k ?>" <?php if($k==$_ccStartMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
	            <?php endforeach ?>
	            </select>
	            <?php $_ccStartYear = $this->getInfoData('cc_start_year') ?>
	            <select id="<?php echo $_code ?>_start_yr" style="width:103px;" name="payment[cc_start_year]">
	            <?php foreach ($this->getCcStartYears() as $k=>$v): ?>
	                <option value="<?php echo $k ? $k : '' ?>" <?php if($k==$_ccStartYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
	            <?php endforeach ?>
	            </select>
	        </div>
	    </li>
	    <li>
	        <div class="input-box">
	            <label for="<?php echo $_code ?>_cc_issue"><?php echo Mage::helper('payment')->__('Issue Number') ?></label><br/>
	            <input type="text" title="<?php echo Mage::helper('payment')->__('Issue Number') ?>" id="<?php echo $_code ?>_cc_issue" name="payment[cc_issue]" style="width:2em;" value="<?php echo $this->getInfoData('cc_issue')?>"/>
	        </div>
	    </li>
	
</ul>
