<?php if($_info = $this->getInfo()): ?>
<?php echo $this->__('Cardholder: %s', $this->getInfo()->getCcOwner()) ?><br />
<?php echo $this->__('Card Type: %s', $this->getCcTypeName()) ?><br />
<?php echo $this->__('Card Number: xxxx-%s', $this->getInfo()->getCcLast4()) ?><br />
<?php echo $this->__('Expiration Date: %02d/%02d', $this->getCcExpMonth(), $this->getInfo()->getCcExpYear()) ?><br />
<?php if($this->getInfo()->getCcSsIssue()): ?>
<?php echo $this->__("Issue Number: %d", $this->getInfo()->getCcSsIssue()) ?><br />
<?php endif; ?>
<?php if($this->getInfo()->getCcSsStartYear()): ?>
<?php echo $this->__('Start Date: %02d/%02d', $this->getInfo()->getCcSsStartMonth(), $this->getInfo()->getCcSsStartYear()) ?>
<?php endif; ?>
<?php endif; ?>